//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C002_AREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C002_AREA()
        {
            this.C003_SUB_AREA = new HashSet<C003_SUB_AREA>();
            this.C004_PROJECT = new HashSet<C004_PROJECT>();
        }
    
        public int AreaId { get; set; }
        public int DivisionId { get; set; }
        public string AreaName { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C003_SUB_AREA> C003_SUB_AREA { get; set; }
        public virtual EndUser EndUser { get; set; }
        public virtual C001_DIVISION C001_DIVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C004_PROJECT> C004_PROJECT { get; set; }
    }
}
