//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C002_TASK_DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C002_TASK_DATA()
        {
            this.C012_Attachments = new HashSet<C012_Attachments>();
            this.C011_coOwners = new HashSet<C011_coOwners>();
            this.C013_CYCLED = new HashSet<C013_CYCLED>();
            this.C003_SUB_TASKS = new HashSet<C003_SUB_TASKS>();
        }
    
        public int TaskId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int LocationId { get; set; }
        public int CompanyId { get; set; }
        public int DivisionId { get; set; }
        public int AreaId { get; set; }
        public int SubAreaId { get; set; }
        public string SName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<double> ManDays { get; set; }
        public int ServiceOwnerId { get; set; }
        public int CreatedById { get; set; }
        public string CreateByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DocsLink { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual C001_PROJECT C001_PROJECT { get; set; }
        public virtual C004_LOCATION C004_LOCATION { get; set; }
        public virtual C010_STATUS C010_STATUS { get; set; }
        public virtual C008_SUB_AREA C008_SUB_AREA { get; set; }
        public virtual C009_TYPE C009_TYPE { get; set; }
        public virtual C007_AREA C007_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C012_Attachments> C012_Attachments { get; set; }
        public virtual C005_COMPANY C005_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C011_coOwners> C011_coOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C013_CYCLED> C013_CYCLED { get; set; }
        public virtual C006_DIVISION C006_DIVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C003_SUB_TASKS> C003_SUB_TASKS { get; set; }
    }
}
