//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C003_SUB_TASKS
    {
        public int SubTaskId { get; set; }
        public int TaskId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int TaskActive { get; set; }
    
        public virtual C002_TASK_DATA C002_TASK_DATA { get; set; }
    }
}
