//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C003_SUB_AREA
    {
        public int SubAreaId { get; set; }
        public int AreaId { get; set; }
        public string SubAreaName { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public bool AreaActive { get; set; }
    
        public virtual C002_AREA C002_AREA { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
