//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C003_SUB_PHASE
    {
        public int SPID { get; set; }
        public int PhaseId { get; set; }
        public int ProjectId { get; set; }
        public string SubPhaseName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime GenerationDate { get; set; }
        public int GenerationBy { get; set; }
    
        public virtual C002_PHASE C002_PHASE { get; set; }
    }
}
