//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C003_SUB_PHASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C003_SUB_PHASE()
        {
            this.C004_BUCKET = new HashSet<C004_BUCKET>();
        }
    
        public int SubPhaseId { get; set; }
        public int ProjectId { get; set; }
        public int PhaseId { get; set; }
        public string SubPhaseName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int GeneratedBy { get; set; }
    
        public virtual C001_PROJECT C001_PROJECT { get; set; }
        public virtual C002_PHASE C002_PHASE { get; set; }
        public virtual EndUser EndUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C004_BUCKET> C004_BUCKET { get; set; }
    }
}
