//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C004_PROJECT
    {
        public int ProjectId { get; set; }
        public int DivisionId { get; set; }
        public int AreaId { get; set; }
        public int SubAreaId { get; set; }
        public string ProjectName { get; set; }
        public int ProjectType { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual C001_DIVISION C001_DIVISION { get; set; }
        public virtual C002_AREA C002_AREA { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
