//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C004_PHASE
    {
        public int PhaseId { get; set; }
        public int ProjectId { get; set; }
        public string PhaseName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int GeneratedBy { get; set; }
    
        public virtual C003_PROJECT C003_PROJECT { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
