//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C004_BUCKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C004_BUCKET()
        {
            this.C005_TASK_DATA = new HashSet<C005_TASK_DATA>();
        }
    
        public int BucketId { get; set; }
        public int ProjectId { get; set; }
        public int PhaseId { get; set; }
        public int SubPhaseId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GenerationDate { get; set; }
    
        public virtual C001_PROJECT C001_PROJECT { get; set; }
        public virtual C002_PHASE C002_PHASE { get; set; }
        public virtual C003_SUB_PHASE C003_SUB_PHASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C005_TASK_DATA> C005_TASK_DATA { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
