//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C005_TASK_DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C005_TASK_DATA()
        {
            this.C019_Attachments = new HashSet<C019_Attachments>();
            this.C018_coOwners = new HashSet<C018_coOwners>();
            this.C016_CYCLED = new HashSet<C016_CYCLED>();
            this.C006_SUB_TASKS = new HashSet<C006_SUB_TASKS>();
        }
    
        public int TaskId { get; set; }
        public int BucketId { get; set; }
        public int AreaId { get; set; }
        public int SubAreaId { get; set; }
        public int SSubAreaId { get; set; }
        public string SName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<double> ManDays { get; set; }
        public int OwnerId { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string DocsLink { get; set; }
        public int TypeId { get; set; }
        public int StatusId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual C010_AREA C010_AREA { get; set; }
        public virtual EndUser EndUser { get; set; }
        public virtual EndUser EndUser1 { get; set; }
        public virtual C015_STATUS C015_STATUS { get; set; }
        public virtual C011_SUB_AREA C011_SUB_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C019_Attachments> C019_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C018_coOwners> C018_coOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C016_CYCLED> C016_CYCLED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C006_SUB_TASKS> C006_SUB_TASKS { get; set; }
        public virtual C014_TASK_TYPE C014_TASK_TYPE { get; set; }
        public virtual C004_BUCKET C004_BUCKET { get; set; }
    }
}
