//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C006_SubPhase
    {
        public int SubPhaseId { get; set; }
        public int PhaseId { get; set; }
        public string SubPhaseName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GeneratedDate { get; set; }
    
        public virtual C005_PHASE C005_PHASE { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
