//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C007_BUCKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C007_BUCKET()
        {
            this.C008_TASK_DATA = new HashSet<C008_TASK_DATA>();
        }
    
        public int BucketId { get; set; }
        public int ProjectId { get; set; }
        public int PhaseId { get; set; }
        public int SubPhaseId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int GeneratedBy { get; set; }
        public System.DateTime GenerationDate { get; set; }
    
        public virtual C005_PHASE C005_PHASE { get; set; }
        public virtual EndUser EndUser { get; set; }
        public virtual C004_PROJECT C004_PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C008_TASK_DATA> C008_TASK_DATA { get; set; }
    }
}
