//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C011_SUB_AREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C011_SUB_AREA()
        {
            this.C005_TASK_DATA = new HashSet<C005_TASK_DATA>();
            this.C012_SUB_SUB_AREA = new HashSet<C012_SUB_SUB_AREA>();
        }
    
        public int SubAreaId { get; set; }
        public int AreaId { get; set; }
        public string SubAreaName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool AreaActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C005_TASK_DATA> C005_TASK_DATA { get; set; }
        public virtual C010_AREA C010_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C012_SUB_SUB_AREA> C012_SUB_SUB_AREA { get; set; }
    }
}
