//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C012_Attachments
    {
        public int AttachId { get; set; }
        public int TaskId { get; set; }
        public string AName { get; set; }
        public Nullable<long> ASize { get; set; }
        public byte[] AContent { get; set; }
        public string AContentType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual C002_TASK_DATA C002_TASK_DATA { get; set; }
    }
}
