//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C013_PROJECT_TYPE
    {
        public int ProjectTypeId { get; set; }
        public string ProjectType { get; set; }
        public bool IsActive { get; set; }
        public int GenerationBy { get; set; }
        public System.DateTime GenerationDate { get; set; }
    }
}
