//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C017_MEETING
    {
        public int MID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> mType { get; set; }
        public string InternalAttendance { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> VendorType { get; set; }
        public Nullable<int> ManDays { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<int> MeetingStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
