//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C018_coOwners
    {
        public int CoOwnerId { get; set; }
        public int ProjectId { get; set; }
        public int UserId { get; set; }
        public string OwnerContribution { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual C003_PROJECT C003_PROJECT { get; set; }
    }
}
