//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C020_CommitmentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C020_CommitmentMaster()
        {
            this.C021_CommimentDetails = new HashSet<C021_CommimentDetails>();
        }
    
        public int CommitmentId { get; set; }
        public int UserId { get; set; }
        public string CommitmentHeader { get; set; }
        public Nullable<int> GeneratedBy { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C021_CommimentDetails> C021_CommimentDetails { get; set; }
    }
}
