//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C023_Notification_Detail
    {
        public int DetailId { get; set; }
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public bool Seen { get; set; }
        public bool IsActive { get; set; }
    
        public virtual C022_Notification_Master C022_Notification_Master { get; set; }
        public virtual EndUser EndUser { get; set; }
    }
}
