//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C001_PROJECT> C001_PROJECT { get; set; }
        public virtual DbSet<C002_TASK_DATA> C002_TASK_DATA { get; set; }
        public virtual DbSet<C003_SUB_TASKS> C003_SUB_TASKS { get; set; }
        public virtual DbSet<C004_LOCATION> C004_LOCATION { get; set; }
        public virtual DbSet<C005_COMPANY> C005_COMPANY { get; set; }
        public virtual DbSet<C006_DIVISION> C006_DIVISION { get; set; }
        public virtual DbSet<C007_AREA> C007_AREA { get; set; }
        public virtual DbSet<C008_SUB_AREA> C008_SUB_AREA { get; set; }
        public virtual DbSet<C009_TYPE> C009_TYPE { get; set; }
        public virtual DbSet<C010_STATUS> C010_STATUS { get; set; }
        public virtual DbSet<C011_coOwners> C011_coOwners { get; set; }
        public virtual DbSet<C012_Attachments> C012_Attachments { get; set; }
        public virtual DbSet<C013_CYCLED> C013_CYCLED { get; set; }
        public virtual DbSet<EndUser> EndUsers { get; set; }
        public virtual DbSet<EndUser_Details> EndUser_Details { get; set; }
        public virtual DbSet<EndUser_LoginDetails> EndUser_LoginDetails { get; set; }
        public virtual DbSet<Mailer_Details> Mailer_Details { get; set; }
        public virtual DbSet<Smart_Login> Smart_Login { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<LOGIN_DETAIL> LOGIN_DETAIL { get; set; }
        public virtual DbSet<vw_SessionUser> vw_SessionUser { get; set; }
    }
}
