//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        public int UID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public bool IsValidLogin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> UserType { get; set; }
        public System.DateTime UserCreated { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Company { get; set; }
    }
}
