//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EndUser()
        {
            this.C005_TASK_DATA = new HashSet<C005_TASK_DATA>();
            this.C005_TASK_DATA1 = new HashSet<C005_TASK_DATA>();
            this.C001_PROJECT = new HashSet<C001_PROJECT>();
        }
    
        public int UID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public bool IsValidLogin { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> UserType { get; set; }
        public System.DateTime UserCreated { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Company { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C005_TASK_DATA> C005_TASK_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C005_TASK_DATA> C005_TASK_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C001_PROJECT> C001_PROJECT { get; set; }
        public virtual C002_PHASE C002_PHASE { get; set; }
    }
}
