//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_DETAIL
    {
        public int RoleDetailId { get; set; }
        public int RoleId { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public bool Allowed { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int GeneratedBy { get; set; }
    
        public virtual ROLE_MASTER ROLE_MASTER { get; set; }
    }
}
