//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smart_Login
    {
        public int SID { get; set; }
        public int UserId { get; set; }
        public System.Guid GUID { get; set; }
        public string ModelName { get; set; }
        public string DeviceName { get; set; }
        public string DeviceUsername { get; set; }
        public decimal ApplicationVersion { get; set; }
        public System.DateTime LoginDateTime { get; set; }
    }
}
