//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PhasebyLCDASAP
    {
        public int PhaseId { get; set; }
        public string PhaseName { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public int SubAreaId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
