//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectListing
    {
        public int ProjectId { get; set; }
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public int SubAreaId { get; set; }
        public string SubAreaName { get; set; }
        public string ProjectName { get; set; }
        public int ProjectType { get; set; }
        public string ProjectTypeName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int GeneratedBy { get; set; }
        public string GeneratedByName { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
