//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Task_Details
    {
        public int TaskId { get; set; }
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public int PhaseId { get; set; }
        public string PhaseName { get; set; }
        public int SubPhaseId { get; set; }
        public string SubPhaseName { get; set; }
        public int BucketId { get; set; }
        public string BucketName { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public int SubAreaId { get; set; }
        public string SubAreaName { get; set; }
        public string SName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<double> ManDays { get; set; }
        public int OwnerId { get; set; }
        public string OwnerName { get; set; }
        public int GeneratedBy { get; set; }
        public string GerneratedName { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string DocsLink { get; set; }
        public int TaskTypeId { get; set; }
        public string TypeName { get; set; }
        public int StatusId { get; set; }
        public string TaskStatus { get; set; }
        public bool IsActive { get; set; }
    }
}
